#!/usr/bin/env bash
# Builds a minimal x86_64 stub for WebRTC.xcframework so that the app can be
# compiled and run on Intel (x86_64) iOS simulators for UI development.
# Calling WebRTC APIs on x86_64 will be a no-op or return nil — voice-room
# functionality is not expected to work on Intel simulators.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEBRTC_XCF="$SCRIPT_DIR/../Frameworks/WebRTC.xcframework"

# Always use the device arm64 slice as source — it's always a thin arm64 binary.
DEVICE_BIN="$WEBRTC_XCF/ios-arm64/WebRTC.framework/WebRTC"
FAT_SLICE="$WEBRTC_XCF/ios-arm64_x86_64-simulator"
FAT_FW="$FAT_SLICE/WebRTC.framework"

if [ ! -f "$DEVICE_BIN" ]; then
  echo "error: Device binary not found at $DEVICE_BIN" >&2; exit 1
fi

TMPDIR_WORK=$(mktemp -d)
trap 'rm -rf "$TMPDIR_WORK"' EXIT

echo "==> Extracting symbols from device arm64 binary..."

# ObjC class names (real names, no suffix)
OBJC_CLASSES=$(xcrun nm -gU -arch arm64 "$DEVICE_BIN" 2>/dev/null \
  | grep 'OBJC_CLASS_\$_' \
  | awk '{print $3}' \
  | sed 's/_OBJC_CLASS_\$_//' || true)

# Plain C function names (T symbols, skip __ internal)
C_FUNCTIONS=$(xcrun nm -gU -arch arm64 "$DEVICE_BIN" 2>/dev/null \
  | grep ' T _[^_]' \
  | awk '{print $3}' \
  | sed 's/^_//' || true)

# Global constant names (any data/section symbol starting with _k)
C_CONSTANTS=$(xcrun nm -gU -arch arm64 "$DEVICE_BIN" 2>/dev/null \
  | grep -E ' [DBRSdsr] _k' \
  | awk '{print $3}' \
  | sed 's/^_//' || true)

echo "==> Generating x86_64 stub source..."
STUB_M="$TMPDIR_WORK/WebRTCStub.m"
cat > "$STUB_M" << 'HEADER'
#import <Foundation/Foundation.h>
// x86_64 stub — all implementations are intentional no-ops.
// Auto-generated by create_webrtc_x86_stub.sh; do not edit manually.
HEADER

echo "" >> "$STUB_M"

# Emit ObjC class stubs using REAL class names so _OBJC_CLASS_$_XXX is exported.
while IFS= read -r cls; do
  [[ -z "$cls" ]] && continue
  printf '@interface %s : NSObject @end\n@implementation %s @end\n' "$cls" "$cls" >> "$STUB_M"
done <<< "$OBJC_CLASSES"

echo "" >> "$STUB_M"

# Emit C function stubs
while IFS= read -r fn; do
  [[ -z "$fn" ]] && continue
  printf '__attribute__((visibility("default"))) void %s(void) {}\n' "$fn" >> "$STUB_M"
done <<< "$C_FUNCTIONS"

echo "" >> "$STUB_M"

# Emit C constant stubs
while IFS= read -r cv; do
  [[ -z "$cv" ]] && continue
  printf '__attribute__((visibility("default"))) void* %s = NULL;\n' "$cv" >> "$STUB_M"
done <<< "$C_CONSTANTS"

echo "==> Compiling stub for x86_64 simulator..."
STUB_O="$TMPDIR_WORK/WebRTCStub.o"
SDK_PATH=$(xcrun --sdk iphonesimulator --show-sdk-path)
xcrun clang \
  -target x86_64-apple-ios14.0-simulator \
  -isysroot "$SDK_PATH" \
  -fobjc-arc \
  -c "$STUB_M" \
  -o "$STUB_O"

echo "==> Linking x86_64 stub dylib..."
STUB_DYLIB="$TMPDIR_WORK/WebRTC_x86_64"
xcrun clang \
  -target x86_64-apple-ios14.0-simulator \
  -isysroot "$SDK_PATH" \
  -dynamiclib \
  -install_name "@rpath/WebRTC.framework/WebRTC" \
  -Xlinker -undefined \
  -Xlinker dynamic_lookup \
  "$STUB_O" \
  -o "$STUB_DYLIB"

echo "==> Creating fat binary (arm64 device + x86_64 stub)..."
FAT_BIN="$TMPDIR_WORK/WebRTC_fat"
# Use the thin arm64 device binary + x86_64 stub to make the simulator fat binary.
lipo -create "$DEVICE_BIN" "$STUB_DYLIB" -output "$FAT_BIN"

echo "==> Installing ios-arm64_x86_64-simulator slice..."
TMP_SLICE="$TMPDIR_WORK/fat_slice"
# Base the new slice on the device framework structure (headers, Info.plist, etc.)
cp -R "$WEBRTC_XCF/ios-arm64" "$TMP_SLICE"
cp "$FAT_BIN" "$TMP_SLICE/WebRTC.framework/WebRTC"
rm -rf "$FAT_SLICE"
mv "$TMP_SLICE" "$FAT_SLICE"

# Remove the old arm64-only simulator slice to avoid "equivalent libraries" error
OLD_SIM="$WEBRTC_XCF/ios-arm64-simulator"
[ -d "$OLD_SIM" ] && rm -rf "$OLD_SIM" && echo "    Removed obsolete ios-arm64-simulator slice."

echo "==> Updating xcframework Info.plist..."
python3 - "$WEBRTC_XCF/Info.plist" << 'PYEOF'
import sys, plistlib, copy

path = sys.argv[1]
with open(path, 'rb') as f:
    plist = plistlib.load(f)

libs = plist['AvailableLibraries']
# Keep only the device slice; rebuild the simulator entry
libs = [l for l in libs if l.get('LibraryIdentifier') not in
        ('ios-arm64-simulator', 'ios-arm64_x86_64-simulator')]

device = next(l for l in libs if l.get('LibraryIdentifier') == 'ios-arm64')
sim = copy.deepcopy(device)
sim['LibraryIdentifier'] = 'ios-arm64_x86_64-simulator'
sim['SupportedArchitectures'] = ['arm64', 'x86_64']
sim['SupportedPlatformVariant'] = 'simulator'
sim.pop('DebugSymbolsPath', None)
libs.append(sim)

plist['AvailableLibraries'] = libs
with open(path, 'wb') as f:
    plistlib.dump(plist, f)
print("Slices:", [l['LibraryIdentifier'] for l in plist['AvailableLibraries']])
PYEOF

echo ""
echo "Done. WebRTC.xcframework now has ios-arm64 + ios-arm64_x86_64-simulator."
